#spring:
#  datasource:
#    url: jdbc:mysql://localhost/readinglist
#    username: dbuser
#    password: dbpass
#    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    root: INFO
---
spring:
  profiles: development
logging:
  level:
    root: DEBUG
---
spring:
  profiles: production
logging:
#  path: /tmp/
#  file: BookWorm.log
  level:
    root: WARN